pipeline {
    agent any
    
	environment { 
        DOCKERHUB_PASS = credentials{'820212Aaa!'}
    }
    stages{
    	stage("Building the student survey image"){
    		steps{
    			script{
		    		checkout scm
		    		sh 'rm -rf *.war'
		    		sh 'jar -cvf Assignment1.war -C WebContent/ .'
		    		sh 'echo ${BUILD_TIMESTAMP}'
		    		sh "docker login -u hshen2 -p ${DOCKERHUB_PASS}"
		    		def customImage = docker.build("hshen2/studentsurvey645:${BUILD_TIMESTAMP}")
		    	}
    		}
    	
    	
    	}
    
        stage ("pushing image to dockerhub") {
            steps {
            	script{
                	sh 'docker push hshen2/studentsurvey645:${BUILD_TIMESTAMP}'
                }
            }
        }
        

    }
}