pipeline {
    agent any
 
	environment { 
        DOCKERHUB_PASS = credentials('password_docker')
    }
    stages{
    	stage("Building the student survey image"){
    		steps{
    			script{
		    		checkout scm
		    		sh 'ls'
		    		sh 'cd Assigment1/src/main/webapp && jar -cvf Assignment.war *'
		    		sh 'echo ${BUILD_TIMESTAMP}'
		    		sh " docker login -u hshen2 -p ${DOCKERHUB_PASS}"
		    		def customImage = docker.build("hshen2/studentsurvey645:${BUILD_TIMESTAMP}")
		    	}
    		}
    	
    	
    	}
    
        stage ("pushing image to dockerhub") {
            steps {
            	script{
                	sh 'docker push hshen2/studentsurvey645:${BUILD_TIMESTAMP}'
                }
            }
        }
        

    }
}